version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    timezone: Europe/Amsterdam
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 0 # in case you don't want to enable version updates
  allow:
    - dependency-type: "production"
