version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    timezone: Europe/Amsterdam
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 10
