name: Deployment template
on:
  workflow_call:
    inputs:
      production_build:
        type: boolean
        default: false
    secrets:
      vercel_token:
        required: false
      vercel_org_id:
        required: false
      vercel_project_id:
        required: false

jobs:
  deploy-release:
    runs-on: ubuntu-latest
    steps:
    - name: Download public directory
      uses: actions/download-artifact@v4
      with:
        name: public
    - name: Publish to Vercel
      uses: BetaHuhn/deploy-to-vercel-action@v1
      with:
        VERCEL_TOKEN: ${{ secrets.vercel_token }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VERCEL_ORG_ID: ${{ secrets.vercel_org_id }}
        VERCEL_PROJECT_ID: ${{ secrets.vercel_project_id }}
        PRODUCTION: ${{ inputs.production_build }}
        ALIAS_DOMAINS: |
          {SHA}.maerteijn.nl
