name: CI template
on: [workflow_call]
jobs:
  run-ci-steps:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Setup nodejs 16.14
      uses: actions/setup-node@v2
      with:
        node-version: 16.14
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install all dependencies
      run: npm ci
    - name: Run eslint
      run: npm run eslint
    - name: Run stylelint
      run: npm run stylelint
    - name: Run prettier
      run: npm run prettier
    - name: Run the unittests
      run: npm run test:unit
    - name: Run the functional tests
      run: npm run test:functional
    - name: Run the e2e tests
      run: npm run test:e2e
    - name: Archive screenshots
      uses: actions/upload-artifact@v1
      with:
        name: screenshots
        path: dist/screenshots

  build-release:
    needs: run-ci-steps
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Setup nodejs 16.14
      uses: actions/setup-node@v2
      with:
        node-version: 16.14
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install all dependencies
      run: npm install
    - name: Create a production build
      run: npm run build
    - name: Archive public directory
      uses: actions/upload-artifact@v1
      with:
        name: public
        path: dist/release
