name: Deployment template
on:
  workflow_call:
    inputs:
      production_build:
        type: boolean
        default: false
    secrets:
      vercel_token:
        required: false
      vercel_org_id:
        required: false
      vercel_project_id:
        required: false

jobs:
  deploy-release:
    runs-on: ubuntu-latest
    steps:
    - name: Download public directory
      uses: actions/download-artifact@v4
      with:
        name: public
    - name: Install Vercel CLI
      run: npm install -g vercel@22.0.1
    - name: Publish to Vercel
      uses: BetaHuhn/deploy-to-vercel-action@latest
      with:
        VERCEL_TOKEN: ${{ secrets.vercel_token }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VERCEL_ORG_ID: ${{ secrets.vercel_org_id }}
        VERCEL_PROJECT_ID: ${{ secrets.vercel_project_id }}
        PRODUCTION: ${{ inputs.production_build }}
        ALIAS_DOMAINS: |
          preview.maerteijn.nl
        PR_PREVIEW_DOMAIN: preview.maerteijn.nl
        VERCEL_SCOPE: 'maerteijns-projects'
