name: Tag with Production deployment
on:
  push:
    tags:
      - '*'

jobs:
  ci-and-build:
    uses: ./.github/workflows/template.yml
    with:
      production_build: true
      trigger_deployment: true
    secrets:
        vercel_token: ${{ secrets.VERCEL_TOKEN }}
        vercel_org_id: ${{ secrets.VERCEL_ORG_ID }}
        vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID }}

