name: maerteijn.nl CI workflow

on: [push, pull_request]
jobs:
  run-ci-steps:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.16
    - run: npm ci
    - run: npm run eslint
    - run: npm run stylelint
    - run: npm run prettier
    - run: npm run test:unit
