name: maerteijn.nl ci
on: [push, pull_request]
jobs:
  run-ci-steps:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Setup nodejs 12.16
      uses: actions/setup-node@v1
      with:
        node-version: 12.16
    - name: Install all dependencies
      run: npm ci
    - name: Run eslint
      run: npm run eslint
    - name: Run stylelint
      run: npm run stylelint
    - name: Run prettier
      run: npm run prettier
    - name: Run the unit and functional tests
      run: npm run test:coverage
    - name: Run the e2e tests
      run: npm run test:e2e
    - name: Archive screenshots
      uses: actions/upload-artifact@v1
      with:
        name: screenshots
        path: dist/e2e/screenshots

