name: maerteijn.nl workflow template
on:
  workflow_call:
    inputs:
      trigger_deployment:
        type: boolean
        default: false
      production_build:
        type: boolean
        default: false
    secrets:
      vercel_token:
        required: false
      vercel_org_id:
        required: false
      vercel_project_id:
        required: false

jobs:
  run-ci-steps:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Setup nodejs 14.15
      uses: actions/setup-node@v1
      with:
        node-version: 14.15
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install all dependencies
      run: npm ci
    - name: Run eslint
      run: npm run eslint
    - name: Run stylelint
      run: npm run stylelint
    - name: Run prettier
      run: npm run prettier
    - name: Run the unittests
      run: npm run test:unit
    - name: Run the functional tests
      run: npm run test:functional
    - name: Run the e2e tests
      run: npm run test:e2e
    - name: Archive screenshots
      uses: actions/upload-artifact@v1
      with:
        name: screenshots
        path: dist/screenshots

  build-release:
    needs: run-ci-steps
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Setup nodejs 14.15
      uses: actions/setup-node@v1
      with:
        node-version: 14.15
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install all dependencies
      run: npm install
    - name: Create a production build
      run: npm run build
    - name: Archive public directory
      uses: actions/upload-artifact@v1
      with:
        name: public
        path: dist/release

  deploy-release:
    if: ${{ inputs.trigger_deployment == true }}
    needs: build-release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Download public directory
      uses: actions/download-artifact@v1
      with:
        name: public
    - name: Deploy to Vercel Action
      uses: BetaHuhn/deploy-to-vercel-action@v1
      with:
        VERCEL_TOKEN: ${{ secrets.vercel_token }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VERCEL_ORG_ID: ${{ secrets.vercel_org_id }}
        VERCEL_PROJECT_ID: ${{ secrets.vercel_project_id }}
        PRODUCTION: ${{ inputs.production_build }}
        ALIAS_DOMAINS: |
          {SHA}.maerteijn.nl
